// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAc9LSO06FBaFlOYfq1DTCA4uPfuVgc3aE',
    appId: '1:947939683255:web:524ff7e4e16b5aa456d632',
    messagingSenderId: '947939683255',
    projectId: 'flutter-62-2024',
    authDomain: 'flutter-62-2024.firebaseapp.com',
    storageBucket: 'flutter-62-2024.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwUvhhFQm8B7Mx4GqXCQePt6QSDsDpErY',
    appId: '1:947939683255:android:b2dcb2e828d9037156d632',
    messagingSenderId: '947939683255',
    projectId: 'flutter-62-2024',
    storageBucket: 'flutter-62-2024.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJGcaYE0vnMXjNQJ5nyyMubUHzq8kWU8A',
    appId: '1:947939683255:ios:4aaaacdc0ab3220f56d632',
    messagingSenderId: '947939683255',
    projectId: 'flutter-62-2024',
    storageBucket: 'flutter-62-2024.appspot.com',
    iosBundleId: 'com.example.tasksApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJGcaYE0vnMXjNQJ5nyyMubUHzq8kWU8A',
    appId: '1:947939683255:ios:4aaaacdc0ab3220f56d632',
    messagingSenderId: '947939683255',
    projectId: 'flutter-62-2024',
    storageBucket: 'flutter-62-2024.appspot.com',
    iosBundleId: 'com.example.tasksApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAc9LSO06FBaFlOYfq1DTCA4uPfuVgc3aE',
    appId: '1:947939683255:web:1b459259e079e08356d632',
    messagingSenderId: '947939683255',
    projectId: 'flutter-62-2024',
    authDomain: 'flutter-62-2024.firebaseapp.com',
    storageBucket: 'flutter-62-2024.appspot.com',
  );

}